apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dj1byyk8l-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dj1byyk8l-python 
  name: dj1byyk8l-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dj1byyk8l-python 
